config/routes.rb
Rails.application.routes.draw do
  get 'twitter/search'
  root to: 'twitter#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twitter_controller.rb
# frozen_string_literal: true

class TwitterController < ApplicationController
  def search
    term = params[:search]
    return unless term.present?

    @tweets = TweetsRetriever.tweets(term)
    @paginatable_tweets = Kaminari.paginate_array(@tweets).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitter_helper.rb
# frozen_string_literal: true

module TwitterHelper
  def top_hashtags(tweets)
    TweetHashtagsCounter.new(tweets).top_hashtags
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/twitter/search.haml
%h1 Search for tweets

= form_tag twitter_search_path, method: :get do
  %p
    = text_field_tag :search, params[:search]
    = submit_tag 'Search'

-if @paginatable_tweets
  - top_hashtags(@tweets).each do |hashtag, count|
    Quantity of "#{hashtag}" hashtag: #{count}
    %br

  %h2 Tweets

  %table
    %tbody
      %tr
        %th Tweet author
        %th Tweet text
    - @paginatable_tweets.each do |tweet|
      %tr
        %td= tweet[:user][:screen_name]
        %td= tweet[:text]

  = paginate @paginatable_tweets
- else
  No tweets found